trigger:
- test

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactStagingDirectory)'
    zipAfterPublish: True

- task: AzureWebApp@1
  inputs:
    azureSubscription: "Tech2 - Microsoft 5(60c7f837-65de-4cf2-aab1-a0e7d24f0b2e)"
    appName: 'bouveteket-test-backend'
    package: $(build.artifactstagingdirectory)/*.zip    
    appType: "webAppLinux"
